### ISSUE TITLE
A way to set up env in current shell instead of needing to create a task script

### ISSUE THREAD

**Issue by dktapps** [php/php-sdk-binary-tools#33]
https://github.com/php/php-sdk-binary-tools/blob/b3d87e1487b9d303b5b122308cb95c4e7dd75497/bin/phpsdk_setshell.bat#L3-L7

I'm building a github actions script and want to use this script to select the correct VS version.

The starter scripts aren't suitable for my case because they require passing a script.bat file to run, and I'd rather write my commands in the workflow file. I ended up echoing my commands into a .bat file in order to run it this way. Seems unnecessarily janky.

I wanted to use setshell to get around this, but the check mentioned above got in my way.

**Comment by cmb69** [comment]
Frankly, I don't quite understand what you want to accomplish. Of course, you just could do
````
set PHP_SDK_RUN_FROM_ROOT=1
phpsdk_setshell.bat v17 x64
````

but that won't work, because the "obnoxious check" is there for a reason.

You could call `vswhere` directly, and then `vcvarsall.bat` with suitable parameters, or just use https://github.com/ilammy/msvc-dev-cmd instead. If you actually need the PHP SDK, setting up a task.bat is somewhat annoying, but probably best for compatibility reasons.

**Comment by dktapps** [comment]
Yeah, previously I've been invoking vcvarsall directly, but it's inconvenient for matching PHP version to toolset version, which is what I want to use setshell for. (That being said, I can see there would be extra steps even if this check wasn't there.)

I guess what I'm really looking for is a way to invoke the starter without having it create a new shell so I don't have to create a task.bat.

**Comment by cmb69** [comment]
If this is about building PHP extensions with Github actions (https://github.com/php/php-src/issues/16843 hints at this), you may want to take a look at https://github.com/php/php-windows-builder and https://github.com/php/setup-php-sdk.

**Comment by dktapps** [comment]
Oh cool thanks @cmb69, I wasn't aware of those actions :)

I was porting an old AppVeyor workflow that used the SDK directly, so it didn't occur to me there might be actions for this. I see it is briefly mentioned on php.net wiki, but with a small note so I didn't see it.

**Comment by dktapps** [comment]
I've since discovered it's probably way less nasty to use the SDK to run wrapper tasks instead of writing my whole build script in cmd, so I no longer have a need for this. Thanks for your help @cmb69

**Comment by cmb69** [comment]
I've thought about this in the meantime, but had not time to pursue. One little thing that might be useful would be a small action which allows to specify a task script and run it. Something like:

````yaml
- uses: run-sdk-task
  with:
    task: |
      buildconf
      configure --enable-whatever …
      nmake
````

But using pre-written task.bat files is certainly a good alternative.
