### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by dktapps** [php/php-sdk-binary-tools#4]
It's been 4 years since 2.2.0 was tagged. I use this toolset in a build script, so it would be nice to have a tag to point it to, instead of a commit hash.

**Comment by cmb69** [comment]
Oh, indeed, we should tag a new release; see also https://github.com/php/php-src/pull/14954#issuecomment-2227355307 ff.

**Comment by cmb69** [comment]
@shivammathur, in my opinion, we should now tag the [current HEAD of the `master` branch](https://github.com/php/php-sdk-binary-tools/commit/d683a0977fe795db99d3129062e4ae014b099882) as `php-sdk-2.3.0`, or is something important still missing? 

I have already prepared https://github.com/php/setup-php-sdk/pull/5, and can update https://github.com/php/php-src/pull/14954 soon. Could you cater to https://github.com/php/php-windows-builder?

**Comment by shivammathur** [comment]
@cmb69 

I have updated php/php-windows-builder in https://github.com/php/php-windows-builder/commit/77afcacf4fcd9e0ff413c20fd32ce552e172e8a4.

**Comment by cmb69** [comment]
[`php-sdk-2.3.0`](https://github.com/php/php-sdk-binary-tools/releases/tag/php-sdk-2.3.0) is available now, so I'm closing this ticket.
