### ISSUE TITLE
About Visual C++ target version

### ISSUE THREAD

**Issue by youkidearitai** [php/php-sdk-binary-tools#6]
Do you intend to support Visual C++ 2022 (or later)?

**Comment by bryan-chenpcm** [comment]
Visual C++ 2022 is supported, it uses vs17 I believe. I saw a commit supporting it.

**Comment by BraisedFish** [comment]
Invoke phpsdk-vc14-x64.bat will find the vs dir, but the condition of vs version is [16,17), so couldn't find the vs dir. it will faild.

D:\var\source\php-sdk-binary-tools-php-sdk-2.2.0\bin\\vswhere -nologo -version "[16,17)" -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -format text
D:\var\source\php-sdk-binary-tools-php-sdk-2.2.0\bin\\vswhere -nologo -version "[16,17)" -products Microsoft.VisualStudio.Product.BuildTools -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -format text
D:\var\source\php-sdk-binary-tools-php-sdk-2.2.0\bin\\vswhere -nologo -version "[16,17)" -prerelease -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -format text

**Comment by cmb69** [comment]
Indeed, Visual Studio 2022 (aka. vs17) is supported as of cc7c11adad5f962f571130cad61f0de2cc071ad7. Just invoke `phpsdk_vs17-x64.bat` to keep going.
